### ISSUE TITLE
TTF support?

### ISSUE THREAD

**Issue by hectorcarranza** [jalkoby/gulp-inline-fonts#2]
Is this plugin able to convert TTF font files?

**Comment by jalkoby** [comment]
yep, just add this:

```js
const gulp = require('gulp');
const inlineFonts = require('gulp-inline-fonts');

gulp.task("font", function() {
  return gulp.src("%your files%")
     .pipe(inlineFonts({ fonts: ['woff', 'woff2', 'ttf', 'eot', 'otf', 'svg'] }))
});
```

also checkout more config [here](https://github.com/jalkoby/gulp-inline-fonts#default-options)

**Comment by jalkoby** [comment]
hey @hectorcarranza . The version 1.0.4 has fixed generation of embedded tff fonts. You can check this out
