### ISSUE TITLE
font-stretch

### ISSUE THREAD

**Issue by nico-martin** [jalkoby/gulp-inline-fonts#7]
Hi there

is there a way to implement the font-stretch property?
https://www.w3schools.com/cssref/css3_pr_font-stretch.asp

Kind regards,
Nico

**Comment by jalkoby** [comment]
Hi Nico. I didn't understand your question - `font-stretch` property used on element, not in "@font-face" declaration

**Comment by nico-martin** [comment]
Hi @jalkoby 

No, you can also use it inside the font-face:
https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp

And that makes sense if you use different font-files for the condensed version.

Kind regards,
Nico

**Comment by jalkoby** [comment]
okay - I don't have now a free time. Probably will do on weekend - you can feel free to make PR

**Comment by nico-martin** [comment]
I just did. I tested it and it should work like this. Would be great if this would be aviable in the node package #8

**Comment by jalkoby** [comment]
#8
